// Command docgen renders the generated documentation fragments and the
// LLM-targeted docs (llms.txt / llms-full.txt) from atteler's own offline,
// credential-free introspection commands.
//
// It is the "code-generated" half of the hybrid documentation: hand-written
// prose pages under docs/ include these fragments via MkDocs snippets, and
// llms-full.txt concatenates the prose with the generated reference so an LLM
// can ingest the whole surface in one file.
//
// Run via `go generate ./...` (the directive below) or `make generate`. The
// output is deterministic; CI's `git diff --exit-code` step fails if a code
// change moves the CLI surface without regenerating these files.
package main

//go:generate go run .

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// docPages is the ordered set of human-readable pages, relative to docs/. The
// order defines the reading order in llms.txt and the concatenation order in
// llms-full.txt. When Phase 2 migrates README prose into new pages, add them
// here so they flow into the LLM docs.
var docPages = []string{
	"index.md",
	"getting-started.md",
	"common-workflows.md",
	"configuration.md",
	"providers.md",
	"hooks.md",
	"cli-reference.md",
	"architecture.md",
	"lifecycle-events.md",
	"symphony.md",
}

const generatedHeader = "<!-- Code generated by `go generate ./internal/docgen`; DO NOT EDIT. -->"

func main() {
	ctx := docgenRootContext{}

	root, err := repoRoot()
	if err != nil {
		fail(err)
	}

	if err := generateFragments(ctx, root); err != nil {
		fail(err)
	}

	if err := generateLLMDocs(root); err != nil {
		fail(err)
	}
}

type docgenRootContext struct{}

func (docgenRootContext) Deadline() (time.Time, bool) { return time.Time{}, false }
func (docgenRootContext) Done() <-chan struct{}       { return nil }
func (docgenRootContext) Err() error                  { return nil }
func (docgenRootContext) Value(any) any               { return nil }

func fail(err error) {
	fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
	os.Exit(1)
}

// repoRoot walks up from the working directory until it finds the module's
// go.mod, so the generator is independent of where `go generate` invokes it.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get working directory: %w", err)
	}

	for {
		if _, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found above %s", dir)
		}

		dir = parent
	}
}

// atteler runs the locally built CLI with the given offline flags and returns
// its stdout. These commands never touch the network or require credentials.
func atteler(ctx context.Context, root string, args ...string) (string, error) {
	full := append([]string{"run", "./cmd/atteler"}, args...)

	cmd := exec.CommandContext(ctx, "go", full...)
	cmd.Dir = root
	cmd.Stderr = os.Stderr

	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("run atteler %v: %w", args, err)
	}

	return string(out), nil
}

// generateFragments writes the deterministic reference fragments that both the
// MkDocs pages and llms-full.txt consume.
func generateFragments(ctx context.Context, root string) error {
	genDir := filepath.Join(root, "docs", "generated")
	if err := os.MkdirAll(genDir, 0o750); err != nil {
		return fmt.Errorf("create generated dir: %w", err)
	}

	surface, err := atteler(ctx, root, "--command-surface-docs")
	if err != nil {
		return err
	}

	err = writeFragment(filepath.Join(genDir, "cli-surface.md"), surface)
	if err != nil {
		return err
	}

	providers, err := atteler(ctx, root, "--list-providers")
	if err != nil {
		return err
	}

	err = writeFragment(filepath.Join(genDir, "providers.md"), renderProviders(providers))
	if err != nil {
		return err
	}

	events, err := atteler(ctx, root, "--list-hook-events-json")
	if err != nil {
		return err
	}

	rendered, err := renderHookEvents(events)
	if err != nil {
		return err
	}

	err = writeFragment(filepath.Join(genDir, "hook-events.md"), rendered)
	if err != nil {
		return err
	}

	options, err := renderCLIOptions(root)
	if err != nil {
		return err
	}

	return writeFragment(filepath.Join(genDir, "cli-options.md"), options)
}

// writeFragment prepends the DO NOT EDIT header (unless the body already starts
// with one) and writes the file.
func writeFragment(path, body string) error {
	body = strings.TrimRight(body, "\n") + "\n"

	var out bytes.Buffer

	if !strings.Contains(firstLines(body, 3), "DO NOT EDIT") {
		fmt.Fprintln(&out, generatedHeader)
		fmt.Fprintln(&out)
	}

	out.WriteString(body)

	if err := os.WriteFile(path, out.Bytes(), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	return nil
}

func firstLines(s string, n int) string {
	lines := strings.SplitN(s, "\n", n+1)
	if len(lines) > n {
		lines = lines[:n]
	}

	return strings.Join(lines, "\n")
}

func renderProviders(raw string) string {
	var out bytes.Buffer

	fmt.Fprintln(&out, "Built-in providers (constructed on demand by the registry; any without")
	fmt.Fprintln(&out, "available credentials are silently skipped at runtime):")
	fmt.Fprintln(&out)

	for name := range strings.FieldsSeq(raw) {
		fmt.Fprintf(&out, "- `%s`\n", name)
	}

	return out.String()
}

type hookEvent struct {
	Type        string `json:"type"`
	Description string `json:"description"`
}

func renderHookEvents(raw string) (string, error) {
	var events []hookEvent
	if err := json.Unmarshal([]byte(raw), &events); err != nil {
		return "", fmt.Errorf("decode hook events: %w", err)
	}

	var out bytes.Buffer

	fmt.Fprintln(&out, "| Event type | Description |")
	fmt.Fprintln(&out, "| --- | --- |")

	for _, e := range events {
		fmt.Fprintf(&out, "| `%s` | %s |\n", e.Type, e.Description)
	}

	return out.String(), nil
}

// snippetInclude matches MkDocs pymdownx.snippets include lines so docgen can
// expand them when flattening pages into llms-full.txt.
var snippetInclude = regexp.MustCompile(`^\s*--8<--\s+"([^"]+)"\s*$`)

func generateLLMDocs(root string) error {
	docsDir := filepath.Join(root, "docs")

	full, index, err := assembleLLMDocs(docsDir)
	if err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(root, "llms-full.txt"), []byte(full), 0o600); err != nil {
		return fmt.Errorf("write llms-full.txt: %w", err)
	}

	if err := os.WriteFile(filepath.Join(root, "llms.txt"), []byte(index), 0o600); err != nil {
		return fmt.Errorf("write llms.txt: %w", err)
	}

	return nil
}

// assembleLLMDocs reads each manifest page, expands snippet includes, and
// returns the flattened llms-full.txt body plus the curated llms.txt index.
func assembleLLMDocs(docsDir string) (fullDoc, indexDoc string, err error) {
	var body bytes.Buffer

	var idx bytes.Buffer

	writeIndexHeader(&idx)

	fmt.Fprintln(&body, "# atteler — full documentation")
	fmt.Fprintln(&body)
	fmt.Fprintln(&body, generatedHeader)

	for _, rel := range docPages {
		raw, readErr := os.ReadFile(filepath.Join(docsDir, rel))
		if readErr != nil {
			return "", "", fmt.Errorf("read page %s: %w", rel, readErr)
		}

		expanded := expandSnippets(string(raw), docsDir)

		fmt.Fprintf(&body, "\n\n---\n\n<!-- source: docs/%s -->\n\n", rel)
		body.WriteString(strings.TrimRight(expanded, "\n"))
		body.WriteString("\n")

		title, desc := pageSummary(expanded)
		fmt.Fprintf(&idx, "- [%s](docs/%s): %s\n", title, rel, desc)
	}

	return body.String(), idx.String(), nil
}

func writeIndexHeader(idx *bytes.Buffer) {
	fmt.Fprintln(idx, "# atteler")
	fmt.Fprintln(idx)
	fmt.Fprintln(idx, "> Go-only LLM harness: a TUI/CLI over multiple providers (anthropic, claude-code,")
	fmt.Fprintln(idx, "> codex, openai, ollama) with sessions, agents, hooks, worktrees, and multi-agent runs.")
	fmt.Fprintln(idx)
	fmt.Fprintln(idx, "This file is generated. `llms-full.txt` contains the full flattened documentation.")
	fmt.Fprintln(idx)
	fmt.Fprintln(idx, "## Documentation")
}

func expandSnippets(content, docsDir string) string {
	var out bytes.Buffer

	for line := range strings.SplitSeq(content, "\n") {
		m := snippetInclude.FindStringSubmatch(line)
		if m == nil {
			fmt.Fprintln(&out, line)
			continue
		}

		frag, err := os.ReadFile(filepath.Join(docsDir, m[1]))
		if err != nil {
			fmt.Fprintln(&out, line)
			continue
		}

		out.WriteString(strings.TrimRight(string(frag), "\n"))
		out.WriteString("\n")
	}

	return out.String()
}

// pageSummary extracts the first H1 as title and the first prose paragraph (or
// blockquote, joining its consecutive lines) as a one-line description for the
// llms.txt index.
func pageSummary(content string) (title, desc string) {
	title = "Untitled"

	var descParts []string

	for line := range strings.SplitSeq(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "<!--") {
			if len(descParts) > 0 {
				break // end of the first paragraph/blockquote
			}

			continue
		}

		if title == "Untitled" && strings.HasPrefix(trimmed, "# ") {
			title = strings.TrimSpace(strings.TrimPrefix(trimmed, "# "))
			continue
		}

		if strings.HasPrefix(trimmed, "#") {
			continue
		}

		descParts = append(descParts, strings.TrimSpace(strings.TrimPrefix(trimmed, ">")))
	}

	desc = strings.TrimSpace(strings.Join(descParts, " "))
	if desc == "" {
		desc = title
	}

	return title, desc
}
