package events

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

//go:generate go run ./internal/eventdocs -out ../../docs/lifecycle-events.md

// EventDoc contains generated documentation examples for one lifecycle event
// type and each payload policy.
//
//nolint:govet // Field order follows generated documentation layout.
type EventDoc struct {
	MetadataExample Event  `json:"metadata_example"`
	SummaryExample  Event  `json:"summary_example"`
	FullExample     Event  `json:"full_example"`
	Type            string `json:"type"`
	Description     string `json:"description"`
	SchemaVersion   int    `json:"schema_version"`
}

var docTimestamp = time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)

// EventDocs returns stable generated examples for every supported event type.
func EventDocs() []EventDoc {
	supported := SupportedEventTypes()
	docs := make([]EventDoc, 0, len(supported))

	for _, supportedType := range supported {
		example := exampleEvent(supportedType.Type)
		docs = append(docs, EventDoc{
			Type:            supportedType.Type,
			Description:     supportedType.Description,
			SchemaVersion:   EventSchemaVersion,
			MetadataExample: sanitizeEventForHook(example, PayloadMetadata),
			SummaryExample:  sanitizeEventForHook(example, PayloadSummary),
			FullExample:     sanitizeEventForHook(example, PayloadFull),
		})
	}

	return docs
}

// EventDocsMarkdown renders EventDocs as stable markdown for checked-in docs.
func EventDocsMarkdown() string {
	var out bytes.Buffer

	fmt.Fprintln(&out, "# Lifecycle hook events")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "<!-- Code generated by `go generate ./pkg/events`; DO NOT EDIT. -->")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "Lifecycle hook payloads use `schema_version: %d` and are filtered through the selected `payload` policy before local hooks receive them.\n", EventSchemaVersion)
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "- `metadata` is the default telemetry-safe payload.")
	fmt.Fprintln(&out, "- `summary` adds generated size/secret summaries for content and error fields.")
	fmt.Fprintln(&out, "- `full` is for trusted hooks and still applies known-secret redaction plus size limits.")
	fmt.Fprintln(&out)

	docs := EventDocs()
	for i := range docs {
		doc := &docs[i]

		fmt.Fprintf(&out, "## `%s`\n\n", doc.Type)
		fmt.Fprintln(&out, doc.Description)
		fmt.Fprintln(&out)
		fmt.Fprintf(&out, "Schema version: `%d`\n\n", doc.SchemaVersion)

		writeExample(&out, "metadata", doc.MetadataExample)
		writeExample(&out, "summary", doc.SummaryExample)
		writeExample(&out, "full", doc.FullExample)
	}

	return strings.TrimRight(out.String(), "\n") + "\n"
}

func writeExample(out *bytes.Buffer, mode string, event Event) {
	fmt.Fprintf(out, "### `%s` example\n\n", mode)
	fmt.Fprintln(out, "```json")

	data, err := json.MarshalIndent(event, "", "  ")
	if err != nil {
		panic(err)
	}

	fmt.Fprintln(out, string(data))
	fmt.Fprintln(out, "```")
	fmt.Fprintln(out)
}

func exampleEvent(eventType string) Event {
	base := Event{
		Timestamp:     docTimestamp,
		SchemaVersion: EventSchemaVersion,
		EventID:       "evt-doc-" + eventType,
		Type:          eventType,
		SessionID:     "session-123",
		SessionPath:   "/home/alice/.atteler/sessions/session-123.json",
		Agent:         "reviewer",
		Model:         "openai/gpt-4.1-mini",
	}

	switch eventType {
	case AgentExecute:
		base.Metadata = map[string]string{"agent": "reviewer"}
	case AssistantMessage:
		base.Role = "assistant"
		base.Content = "The build passed after updating the test fixture."
	case CommandExecute:
		base.Content = "go test ./pkg/events"
		base.Metadata = map[string]string{
			"command":      "go test ./pkg/events",
			"cwd":          "/home/alice/project",
			"provider":     "codex",
			"source":       "llm_tool",
			"tool_call_id": "call_123",
		}
	case CommandOutput:
		base.Content = "$ go test ./pkg/events\nok"
		base.Error = "exit status 1"
		base.Metadata = map[string]string{
			"command":      "go test ./pkg/events",
			"cwd":          "/home/alice/project",
			"partial":      "false",
			"sequence":     "1",
			"source":       "llm_tool",
			"stream":       "stdout",
			"tool_call_id": "call_123",
		}
	case ContextAdd:
		base.Metadata = map[string]string{"kind": "file", "path": "/home/alice/project/README.md", "bytes": "1200"}
	case ContextManifest:
		base.Metadata = map[string]string{
			"context_manifest":             `{"schema_version":1,"included_reference_count":1}`,
			"context_summary":              "agent=1,file=1",
			"estimated_tokens":             "640",
			"included_reference_count":     "1",
			"model_context_window_checked": "true",
			"request_kind":                 "chat",
			"schema_version":               "1",
		}
	case Error:
		base.Error = "provider returned HTTP 429"
	case FileRead:
		base.Metadata = map[string]string{"kind": "file", "path": "/home/alice/project/README.md", "bytes": "1200"}
	case FileWrite:
		base.Metadata = map[string]string{"kind": "session", "path": "/home/alice/.atteler/sessions/session-123.json"}
	case RouteDecision:
		base.Content = `{"selected":"openai/gpt-4.1-mini","rejected_count":2}`
		base.Metadata = map[string]string{
			"candidate_count":  "3",
			"estimated_cost":   "0.0004",
			"estimated_tokens": "1200",
			"phase":            "estimated",
			"provider_count":   "2",
			"rejected_count":   "2",
			"selected":         "openai/gpt-4.1-mini",
			"warning_count":    "0",
		}
	case SessionEnd:
		base.Metadata = map[string]string{"agent_loop_budget": `{"max_iterations":4}`}
	case SessionStart:
		base.Metadata = map[string]string{"agent_loop_budget": `{"max_iterations":4}`}
	case ToolExecute:
		base.Metadata = map[string]string{"provider": "codex", "tool": "shell.run", "option_adjustments": "0"}
	case UserMessage:
		base.Role = "user"
		base.Content = "Please review @README.md before running tests."
		base.Metadata = map[string]string{"context_references": "README.md"}
	}

	return base
}
