package main

import (
	"flag"

	atteval "github.com/tommoulard/atteler/pkg/eval"
)

func registerCLIFlags(opts *cliOptions) {
	registerCLIFlagsWithFlagSet(flag.CommandLine, opts)
}

func registerCLIFlagsWithFlagSet(fs *flag.FlagSet, opts *cliOptions) {
	fs.StringVar(&opts.configPaths, "config", "", "additional YAML/JSON config file path(s); same format as ATTELER_CONFIG")
	fs.StringVar(&opts.contextPackPath, "context-pack-file", "", "compact a role-prefixed transcript file and exit")
	fs.StringVar(&opts.initConfigPath, "init-config", "", "write a starter YAML config to this path without overwriting")
	fs.StringVar(&opts.sessionDir, "session-dir", "", "directory for session JSON files")
	fs.StringVar(&opts.sessionRef, "session", "", "session ID or path to continue")
	fs.StringVar(&opts.sessionRef, "session-id", "", "alias for --session")
	fs.StringVar(&opts.showSessionRef, "show-session", "", "print saved session details as YAML and exit")
	fs.StringVar(&opts.summarySessionRef, "session-summary", "", "print compact saved session metadata and counts and exit")
	fs.StringVar(&opts.sessionTitle, "session-title", "", "set or update the saved session title")
	fs.Var(&opts.sessionTags, "session-tag", "add a saved session tag (repeatable or comma-separated)")
	fs.StringVar(&opts.replayRef, "replay", "", "session ID or path to print and exit")
	fs.StringVar(&opts.exportRef, "export-session", "", "session ID or path to export and exit")
	fs.StringVar(&opts.exportFormat, "export-format", "markdown", "session export format: markdown, json, private-markdown, private-json, issue, issue-json; run exports also accept text, replay, or resume")
	fs.StringVar(&opts.showRunRef, "show-run", "", "multi-agent run ID, latest, review, or speculation to show as YAML on the selected session")
	fs.StringVar(&opts.exportRunRef, "export-run", "", "multi-agent run ID, latest, review, or speculation to export from the selected session")
	fs.StringVar(&opts.replayRunRef, "replay-run", "", "multi-agent run ID, latest, review, or speculation to replay without provider calls")
	fs.StringVar(&opts.resumeRunRef, "resume-run", "", "multi-agent run ID, latest, review, or speculation to resume from recorded artifacts without provider calls")
	fs.StringVar(&opts.outputFormat, outputFlagName, outputFormatText, "one-shot output format: text or json")
	fs.BoolVar(&opts.jsonOutput, "json", false, "emit JSON for commands with structured output, such as code-intel")
	fs.StringVar(&opts.searchQuery, "search-sessions", "", "search saved session transcripts and exit")
	fs.StringVar(&opts.oncePrompt, "once", "", "send one prompt and exit")
	fs.StringVar(&opts.model, "model", "", "model ID to use")
	fs.StringVar(&opts.agentName, "agent", "", "agent name to use for prompts")
	fs.StringVar(&opts.describeAgentName, "describe-agent", "", "print a configured agent as YAML and exit")
	fs.StringVar(&opts.codeSymbolName, "code-symbol", "", "find Go symbols by exact name in the current repository and exit")
	fs.Var(&opts.codeLimit, "code-limit", "maximum code-intel rows to emit for list-style results")
	fs.Var(&opts.codeOffset, "code-offset", "number of code-intel rows to skip before emitting list-style results")
	fs.StringVar(&opts.codeSymbolFileSummary, "code-symbol-name-file-summary", "", "list Go files with symbol counts for this exact name and exit")
	fs.StringVar(&opts.codeSymbolPackageSummary, "code-symbol-name-package-summary", "", "list Go packages with file and symbol counts for this exact name and exit")
	fs.StringVar(&opts.codeSymbolPrefix, "code-symbol-prefix", "", "find Go symbols by name prefix in the current repository and exit")
	fs.StringVar(&opts.codeSymbolPrefixFileSummary, "code-symbol-prefix-file-summary", "", "list Go files with symbol counts for names matching this prefix and exit")
	fs.StringVar(&opts.codeSymbolPrefixPackageSummary, "code-symbol-prefix-package-summary", "", "list Go packages with file and symbol counts for names matching this prefix and exit")
	fs.StringVar(&opts.codeSymbolKind, "code-symbol-kind", "", "list Go symbols by kind (func, method, type, const, var) and exit")
	fs.StringVar(&opts.codeSymbolKindFileSummary, "code-symbol-kind-file-summary", "", "list Go files with symbol counts for one kind and exit")
	fs.StringVar(&opts.codeSymbolKindPackageSummary, "code-symbol-kind-package-summary", "", "list Go packages with file and symbol counts for one kind and exit")
	fs.StringVar(&opts.codeImpactTarget, "code-impact", "", "list Go files that directly or transitively import this path and exit")
	fs.StringVar(&opts.codeImportPath, "code-import-path", "", "list Go files that directly import this import path and exit")
	fs.StringVar(&opts.codeImportPathSummary, "code-import-path-summary", "", "summarize file usage count for one exact import path and exit")
	fs.StringVar(&opts.codeImportPathFileSummary, "code-import-path-file-summary", "", "list Go files with import counts for one exact import path and exit")
	fs.StringVar(&opts.codeImportPathPackageSummary, "code-import-path-package-summary", "", "list Go packages with file counts for one exact import path and exit")
	fs.StringVar(&opts.codeImportPrefix, "code-import-prefix", "", "list Go files that directly import paths with this prefix and exit")
	fs.StringVar(&opts.codeImportPrefixSummary, "code-import-prefix-summary", "", "summarize import usage counts for paths with this prefix and exit")
	fs.StringVar(&opts.codeImportPrefixFileSummary, "code-import-prefix-file-summary", "", "list Go files with import counts for paths matching this prefix and exit")
	fs.StringVar(&opts.codeImportPrefixPackageSummary, "code-import-prefix-package-summary", "", "list Go packages with file and import counts for paths matching this prefix and exit")
	fs.StringVar(&opts.codeReachTarget, "code-reachable", "", "list Go import graph nodes reachable from this file path or import path and exit")
	fs.StringVar(&opts.codeDepsTarget, "code-deps", "", "list direct Go import graph dependencies for this file path or import path and exit")
	fs.StringVar(&opts.codeRdepsTarget, "code-rdeps", "", "list direct Go import graph reverse dependencies for this file path or import path and exit")
	fs.StringVar(&opts.codePackageName, "code-package", "", "list Go files and symbol counts for one package and exit")
	fs.StringVar(&opts.codePackageImports, "code-package-imports", "", "list import usage counts for one Go package and exit")
	fs.StringVar(&opts.codePackageImportPath, "code-package-import-path", "", "list exact import usage for one package as package:import and exit")
	fs.StringVar(&opts.codePackageImportFiles, "code-package-import-files", "", "list files in one package importing an exact path as package:import and exit")
	fs.StringVar(&opts.codePackageImportPathFileSummary, "code-package-import-path-file-summary", "", "list files in one package with import counts for package:import and exit")
	fs.StringVar(&opts.codePackageImportPrefix, "code-package-import-prefix", "", "list import usage for one package and import prefix as package:prefix and exit")
	fs.StringVar(&opts.codePackageImportPrefixFiles, "code-package-import-prefix-files", "", "list files in one package importing paths with prefix as package:prefix and exit")
	fs.StringVar(&opts.codePackageImportPrefixFileSummary, "code-package-import-prefix-file-summary", "", "list files in one package with import counts for paths matching package:prefix and exit")
	fs.StringVar(&opts.codePackageImportFileSummary, "code-package-import-file-summary", "", "list files in one Go package with import counts and exit")
	fs.StringVar(&opts.codePackageSymbols, "code-package-symbols", "", "list symbol kind counts for one Go package and exit")
	fs.StringVar(&opts.codePackageSymbolFileSummary, "code-package-symbol-file-summary", "", "list files in one Go package with symbol counts and exit")
	fs.StringVar(&opts.codePackageSymbolName, "code-package-symbol", "", "list Go symbols for one package and exact name as package:name and exit")
	fs.StringVar(&opts.codePackageSymbolNameFileSummary, "code-package-symbol-name-file-summary", "", "list files in one Go package with symbol counts for package:name and exit")
	fs.StringVar(&opts.codePackageSymbolList, "code-package-symbol-list", "", "list Go symbols declared in one package and exit")
	fs.StringVar(&opts.codePackageSymbolKind, "code-package-symbol-kind", "", "list Go symbols for one package and kind as package:kind and exit")
	fs.StringVar(&opts.codePackageSymbolKindFileSummary, "code-package-symbol-kind-file-summary", "", "list files in one Go package with symbol counts for package:kind and exit")
	fs.StringVar(&opts.codePackageSymbolPrefix, "code-package-symbol-prefix", "", "list Go symbols for one package and name prefix as package:prefix and exit")
	fs.StringVar(&opts.codePackageSymbolPrefixFileSummary, "code-package-symbol-prefix-file-summary", "", "list files in one Go package with symbol counts for package:prefix and exit")
	fs.StringVar(&opts.codeFilePath, "code-file", "", "print Go package, symbols, and imports for one file and exit")
	fs.StringVar(&opts.codeFileImports, "code-file-imports", "", "list imports for one Go file and exit")
	fs.StringVar(&opts.codeFileSymbols, "code-file-symbols", "", "list symbols for one Go file and exit")
	fs.StringVar(&opts.codeFileSymbolSummary, "code-file-symbol-summary", "", "list symbol kind counts for one Go file and exit")
	fs.StringVar(&opts.codeFileSymbolName, "code-file-symbol", "", "list Go symbols for one file and exact name as path:name and exit")
	fs.StringVar(&opts.codeFileSymbolKind, "code-file-symbol-kind", "", "list Go symbols for one file and kind as path:kind and exit")
	fs.StringVar(&opts.codeFileSymbolPrefix, "code-file-symbol-prefix", "", "list Go symbols for one file and name prefix as path:prefix and exit")
	fs.StringVar(&opts.codeFileImportPrefix, "code-file-import-prefix", "", "list imports for one Go file matching path:prefix and exit")
	fs.StringVar(&opts.codeFileImportPath, "code-file-import-path", "", "check/list one Go file import as path:import and exit")
	fs.StringVar(&opts.recordFailure, "record-failure", "", "record a failed approach/negative-knowledge note on the selected session and exit")
	fs.StringVar(&opts.failureReason, "failure-reason", "", "reason for --record-failure")
	fs.StringVar(&opts.failureCommit, "failure-commit", "", "commit or reference associated with --record-failure")
	fs.StringVar(&opts.failureTaskType, "failure-task-type", "", "task class for --record-failure")
	fs.StringVar(&opts.failureSeverity, "failure-severity", "", "severity for --record-failure")
	fs.StringVar(&opts.recordEvaluation, "record-evaluation", "", "record an evaluation for this agent on the selected session and exit")
	fs.StringVar(&opts.evaluationOutcome, "evaluation-outcome", "", "outcome for --record-evaluation")
	fs.StringVar(&opts.evaluationNotes, "evaluation-notes", "", "notes for --record-evaluation")
	fs.StringVar(&opts.evaluationReference, "evaluation-reference", "", "reference for --record-evaluation")
	fs.StringVar(&opts.evaluationSource, "evaluation-source", "", "provenance for --record-evaluation: human, harness, or ci")
	fs.StringVar(&opts.evaluationEvaluator, "evaluation-evaluator", "", "evaluator identity for --record-evaluation")
	fs.StringVar(&opts.evaluationRubricVersion, "evaluation-rubric-version", "", "versioned rubric identifier for --record-evaluation")
	fs.StringVar(&opts.evaluationTaskType, "evaluation-task-type", "", "task class for --record-evaluation")
	fs.StringVar(&opts.evaluationDifficulty, "evaluation-difficulty", "", "difficulty label for --record-evaluation")
	fs.StringVar(&opts.evaluationExpectedOutcome, "evaluation-expected-outcome", "", "expected outcome for --record-evaluation")
	fs.StringVar(&opts.evaluationProvider, "evaluation-provider", "", "provider identifier for --record-evaluation")
	fs.StringVar(&opts.evaluationModel, "evaluation-model", "", "model identifier for --record-evaluation")
	fs.StringVar(&opts.evaluationFixtureVersion, "evaluation-fixture-version", "", "fixture version for --record-evaluation")
	fs.StringVar(&opts.evaluationAgentVersion, "evaluation-agent-version", "", "agent version identifier for --record-evaluation")
	fs.StringVar(&opts.evaluationReportPath, "evaluation-report", "", "machine-readable eval report JSON to populate --record-evaluation metrics")
	fs.StringVar(&opts.planAgentsPrompt, "plan-agents", "", "plan configured agents for this prompt and exit")
	fs.Var(&opts.planAgentNames, "plan-agent", "explicit agent name to include in --plan-agents (repeatable or comma-separated)")
	fs.Var(&opts.planMaxAgents, "plan-max-agents", "maximum agents to include in --plan-agents")
	fs.StringVar(&opts.evalOutputPath, "eval-output", "", "actual output file to compare and exit")
	fs.StringVar(&opts.evalAssertionsPath, "eval-assertions", "", "YAML/JSON structured assertion file for --eval-output")
	fs.StringVar(&opts.evalFixtureDir, "eval-fixture-dir", "", "directory of structured eval fixtures to discover and run")
	fs.StringVar(&opts.evalReportPath, "eval-report", "", "write machine-readable eval report JSON to this path")
	fs.StringVar(&opts.evalExpected, "eval-expected", "", "expected text for --eval-output")
	fs.StringVar(&opts.evalExpectedPath, "eval-expected-file", "", "expected output file for --eval-output")
	fs.StringVar(&opts.evalMode, "eval-mode", string(atteval.ModeContains), "eval mode: exact, contains, or normalized")
	fs.Var(&opts.evalExitCode, "eval-exit-code", "actual process exit code available to structured eval assertions")
	fs.BoolVar(&opts.evalJSON, "eval-json", false, "print machine-readable eval report JSON")
	fs.BoolVar(&opts.evalUpdateGolden, "eval-update-golden", false, "update golden files from actual output")
	fs.BoolVar(&opts.evalApproveGoldenUpdate, "eval-approve-golden-update", false, "confirm reviewed golden updates for --eval-update-golden")
	fs.StringVar(&opts.gitHistorySearch, "git-history-search", "", "search local git history subjects/files/authors and exit")
	fs.Var(&opts.gitHistoryLimit, "git-history-limit", "maximum --git-history-search results")
	fs.StringVar(&opts.describePluginName, "describe-plugin", "", "print a configured plugin manifest as YAML and exit")
	fs.StringVar(&opts.runPluginTarget, "run-plugin", "", "run configured plugin name, or plugin/entrypoint when --plugin-entrypoint is omitted")
	fs.StringVar(&opts.pluginEntrypoint, "plugin-entrypoint", "", "entrypoint name for --run-plugin")
	fs.StringVar(&opts.initRTKPluginDir, "init-rtk-plugin", "", "write an RTK plugin scaffold to this directory and exit")
	fs.Var(&opts.pluginTimeout, "plugin-timeout-seconds", "timeout in seconds for --run-plugin")
	fs.BoolVar(&opts.pluginDryRun, "plugin-dry-run", false, "describe --run-plugin without executing it")
	fs.StringVar(&opts.bashCommand, "bash", "", "run an explicit local bash command and exit")
	fs.StringVar(&opts.bashDir, "bash-dir", "", "working directory for --bash")
	fs.Var(&opts.bashTimeout, "bash-timeout-seconds", "timeout in seconds for --bash")
	fs.StringVar(&opts.taskFilePath, "task-file", "", "JSON task-list file; defaults to .atteler/tasks.json")
	fs.StringVar(&opts.taskAddTitle, "task-add", "", "add a persistent agent task/TODO item and exit")
	fs.StringVar(&opts.taskAddID, "task-id", "", "optional stable ID for --task-add")
	fs.StringVar(&opts.taskAgent, "task-agent", "", "agent for --task-add or --task-complete")
	fs.StringVar(&opts.taskAssignSpec, "task-assign", "", "assign a task as id:agent and exit")
	fs.StringVar(&opts.taskCompleteID, "task-complete", "", "mark a task complete by ID and exit")
	fs.StringVar(&opts.memorySearch, "memory-search", "", "search scoped local memory from selected sessions, --memory-store, and --memory-index files")
	fs.StringVar(&opts.memoryStorePath, "memory-store", "", "JSON memory store path to load and/or save")
	fs.StringVar(&opts.memoryDelete, "memory-delete", "", "delete one document ID from a JSON memory store and exit")
	fs.BoolVar(&opts.memoryCompact, "memory-compact", false, "remove expired documents from a JSON memory store and exit")
	fs.BoolVar(&opts.memoryMigrate, "memory-migrate", false, "explicitly migrate and redact a JSON memory store")
	fs.BoolVar(&opts.memoryIncludeSessionMessages, "memory-include-session-messages", false, "opt in to indexing raw saved-session messages into local memory after redaction")
	fs.BoolVar(&opts.memoryIncludeWorktreeMetadata, "memory-include-worktree-metadata", false, "opt in to indexing saved-session worktree paths and branches into local memory after redaction")
	fs.StringVar(&opts.memoryScope, "memory-scope", "", "memory corpus scope: session, repo, tags, date-range, agent, global, or store")
	fs.StringVar(&opts.memorySessionRef, "memory-session", "", "session ID or path for session-scoped memory")
	fs.StringVar(&opts.memoryRepoPath, "memory-repo", "", "repository/worktree path for repo-scoped memory; defaults to git root or cwd")
	fs.Var(&opts.memoryTags, "memory-tag", "session tag for tagged memory scope (repeatable or comma-separated)")
	fs.StringVar(&opts.memorySince, "memory-since", "", "include sessions updated on/after this date (YYYY-MM-DD or RFC3339)")
	fs.StringVar(&opts.memoryUntil, "memory-until", "", "include sessions updated on/before this date (YYYY-MM-DD or RFC3339)")
	fs.StringVar(&opts.memoryAgent, "memory-agent", "", "agent name for agent-scoped session memory; defaults to --agent when --memory-scope agent")
	fs.BoolVar(&opts.memoryGlobal, "memory-global", false, "opt in to all saved sessions for memory search/rebuild")
	fs.StringVar(&opts.memoryPurgeSpec, "memory-purge", "", "purge memory documents by session:<id>, tag:<tag>, repo:<path>, or all")
	fs.BoolVar(&opts.memoryRebuild, "memory-rebuild", false, "rebuild --memory-store from the selected memory corpus")
	fs.BoolVar(&opts.memoryListCorpus, "memory-list-corpus", false, "print memory corpus metadata and document counts")
	fs.Var(&opts.memoryRedactRules, "memory-redact", "custom RE2 regexp to redact from memory before indexing/printing (repeatable)")
	fs.Var(&opts.memoryRetentionDays, "memory-retention-days", "retention window in days for indexed session documents")
	fs.StringVar(&opts.retrievalSearch, "retrieval-search", "", "search selected retrieval sources under the shared result contract and exit")
	fs.Var(&opts.retrievalSources, "retrieval-source", "retrieval source to search: memory, file, session, git, vector, agent-memory, or all (repeatable or comma-separated)")
	fs.Var(&opts.retrievalFilters, "retrieval-filter", "exact retrieval filter as key=value, e.g. agent=reviewer or source.name=session-id (repeatable)")
	fs.Var(&opts.retrievalLimit, "retrieval-limit", "maximum --retrieval-search results")
	fs.BoolVar(&opts.retrievalExplain, "retrieval-explain", false, "include ranking explanations in --retrieval-search output")
	fs.BoolVar(&opts.retrievalIncludeUnsafe, "retrieval-include-unsafe", false, "include retrieval results not safe for prompt injection")
	fs.StringVar(&opts.mcpManifestPath, "mcp-manifest", "", "validate/list or invoke an MCP manifest YAML/JSON file and exit")
	fs.StringVar(&opts.mcpCapability, "mcp-capability", "", "find servers declaring this capability in --mcp-manifest")
	fs.StringVar(&opts.mcpServerName, "mcp-server", "", "server name in --mcp-manifest for --mcp-method or --mcp-tool")
	fs.StringVar(&opts.mcpMethod, "mcp-method", "", "invoke this JSON-RPC method on --mcp-server")
	fs.StringVar(&opts.mcpParamsJSON, "mcp-params", "", "JSON params for --mcp-method")
	fs.StringVar(&opts.mcpToolName, "mcp-tool", "", "invoke this MCP tool through tools/call on --mcp-server")
	fs.StringVar(&opts.mcpToolArgsJSON, "mcp-tool-args", "", "JSON object arguments for --mcp-tool")
	fs.Var(&opts.mcpTimeout, "mcp-timeout-seconds", "timeout in seconds for --mcp-method or --mcp-tool")
	fs.Var(&opts.memoryIndexFiles, "memory-index", "file to add to memory before saving/searching (repeatable or comma-separated)")
	fs.Var(&opts.memoryLimit, "memory-limit", "maximum memory search results")
	fs.Var(&opts.memoryTTL, "memory-ttl-seconds", "expire newly indexed memory after this many seconds")
	fs.StringVar(&opts.agentMemoryStorePath, "agent-memory-store", "", "JSON store for per-agent lexical memory")
	fs.StringVar(&opts.agentMemoryAgent, "agent-memory-agent", "", "agent namespace for per-agent lexical memory; defaults to --agent")
	fs.StringVar(&opts.agentMemorySearch, "agent-memory-search", "", "search one agent's lexical memory and exit")
	fs.StringVar(&opts.agentMemoryDelete, "agent-memory-delete", "", "delete one document ID from one agent's lexical memory and exit")
	fs.BoolVar(&opts.agentMemoryCompact, "agent-memory-compact", false, "remove expired documents from per-agent lexical memory and exit")
	fs.BoolVar(&opts.agentMemoryMigrate, "agent-memory-migrate", false, "explicitly migrate and re-vectorize a per-agent lexical memory store")
	fs.Var(&opts.agentMemoryIndexFiles, "agent-memory-index", "file to add to one agent's lexical memory (repeatable or comma-separated)")
	fs.Var(&opts.agentMemoryTTL, "agent-memory-ttl-seconds", "expire newly indexed agent memory after this many seconds")
	fs.Var(&opts.agentMemoryLimit, "agent-memory-limit", "maximum per-agent memory search results")
	fs.StringVar(&opts.vectorSearch, "vector-search", "", "search a local vector index and exit")
	fs.Var(&opts.vectorIndexFiles, "vector-index", "UTF-8 file to add to the persisted vector index (repeatable or comma-separated)")
	fs.StringVar(&opts.vectorStorePath, "vector-store", "", "JSON vector index path; defaults to vector.index_path or .atteler/vector-index.json")
	fs.StringVar(&opts.vectorizer, "vectorizer", "", "vector retrieval mode: lexical or embedding")
	fs.StringVar(&opts.vectorProvider, "vector-provider", "", "embedding provider label; currently ollama-compatible")
	fs.StringVar(&opts.vectorModel, "vector-model", "", "embedding model name")
	fs.StringVar(&opts.vectorBaseURL, "vector-base-url", "", "embedding API base URL")
	fs.Var(&opts.vectorTimeout, "vector-timeout-seconds", "embedding request timeout in seconds")
	fs.StringVar(&opts.vectorFallbackPolicy, "vector-fallback", "", "embedding failure policy: fail or lexical")
	fs.Var(&opts.vectorChunkMaxRunes, "vector-chunk-max-runes", "maximum runes per indexed vector chunk")
	fs.Var(&opts.vectorChunkOverlapRunes, "vector-chunk-overlap-runes", "overlap runes between indexed vector chunks")
	fs.Var(&opts.vectorLimit, "vector-limit", "maximum vector search results")
	fs.BoolVar(&opts.lspSymbols, "lsp-symbols", false, "request document symbols from an external language server and exit")
	fs.StringVar(&opts.lspWorkspaceSymbols, "lsp-workspace-symbols", "", "query workspace symbols from an external language server and exit")
	fs.StringVar(&opts.lspCommand, "lsp-command", "", "language server command for --lsp-symbols or --lsp-workspace-symbols")
	fs.Var(&opts.lspArgs, "lsp-arg", "language server argument for LSP commands (repeatable)")
	fs.StringVar(&opts.lspFilePath, "lsp-file", "", "source file to inspect with --lsp-symbols")
	fs.StringVar(&opts.lspRootPath, "lsp-root", "", "workspace root for --lsp-symbols")
	fs.StringVar(&opts.lspLanguageID, "lsp-language", "", "language ID for --lsp-symbols; inferred from --lsp-file when omitted")
	fs.StringVar(&opts.promptCompleteInput, "prompt-complete", "", "suggest local prompt completions with context freshness and exit")
	fs.Var(&opts.promptCompleteLimit, "prompt-complete-limit", "maximum --prompt-complete suggestions")
	fs.BoolVar(&opts.promptLocalOnly, "prompt-local-only", false, "force local prompt completions only; model-backed idle suggestions are opt-in via /suggestions")
	fs.BoolVar(&opts.asyncPlan, "async-plan", false, "print dependency-aware async task batches and exit")
	fs.BoolVar(&opts.asyncRun, "async-run", false, "execute dependency-aware async tasks by spawning Atteler sub-agents and exit")
	fs.Var(&opts.asyncTaskSpecs, "async-task", "task spec for --async-plan/--async-run: id|agent|prompt|dep1+dep2 (repeatable or comma-separated)")
	fs.Var(&opts.spawnAgentSpecs, "spawn-agent", "spawn sub-agent spec: id|agent|prompt or agent|prompt (repeatable)")
	fs.BoolVar(&opts.spawnDryRun, "spawn-dry-run", false, "print --spawn-agent invocations without executing them")
	fs.StringVar(&opts.spawnBinary, "spawn-binary", "", "atteler binary for --spawn-agent; defaults to the current executable")
	fs.Var(&opts.spawnTimeout, "spawn-timeout-seconds", "overall timeout in seconds for --spawn-agent/--async-run")
	fs.Var(&opts.spawnTaskTimeout, "spawn-task-timeout-seconds", "per-child timeout in seconds for --spawn-agent/--async-run")
	fs.Var(&opts.spawnMaxConcurrency, "spawn-max-concurrency", "maximum concurrent child processes for --spawn-agent/--async-run")
	fs.Var(&opts.spawnRetries, "spawn-retries", "retry count per child for --spawn-agent/--async-run")
	fs.Var(&opts.spawnRetryBackoff, "spawn-retry-backoff-seconds", "retry backoff in seconds for --spawn-agent/--async-run")
	fs.BoolVar(&opts.spawnCancelOnFailure, "spawn-cancel-on-failure", false, "cancel same-wave/sibling child work after the first failure")
	fs.Var(&opts.spawnTokenBudget, "spawn-token-budget", "aggregate estimated prompt-token budget for --spawn-agent/--async-run")
	fs.Var(&opts.spawnCostBudgetMicros, "spawn-cost-budget-micros", "aggregate estimated cost budget in micros for --spawn-agent/--async-run")
	fs.Var(&opts.spawnOutputBudgetBytes, "spawn-output-budget-bytes", "aggregate stdout/stderr byte budget for --spawn-agent/--async-run")
	fs.StringVar(&opts.spawnLedgerPath, "spawn-ledger", "", "JSON execution ledger path for --spawn-agent/--async-run; defaults under .atteler/runs")
	fs.BoolVar(&opts.spawnResume, "spawn-resume", false, "resume matching successful children from --spawn-ledger without rerunning them")
	fs.Var(&opts.suggestSkillSteps, "skill-step", "observed action for skill suggestion; optionally append |prompt=...|tool=...|input=...|output=...|verify=...|stop=...")
	fs.StringVar(&opts.skillSaveDir, "skill-save-dir", "", "persist accepted --skill-step suggestion as a reviewed skill directory")
	fs.BoolVar(&opts.skillReviewOnly, "skill-review-only", false, "print generated --skill-save-dir skill diff without writing files")
	fs.BoolVar(&opts.skillLearningList, "skill-learning-list", false, "list automatically generated skills and learning status")
	fs.StringVar(&opts.skillLearningShow, "skill-learning-show", "", "print one automatically generated skill by slug")
	fs.StringVar(&opts.skillLearningEdit, "skill-learning-edit", "", "open one automatically generated skill in $VISUAL or $EDITOR by slug")
	fs.StringVar(&opts.skillLearningEnable, "skill-learning-enable", "", "enable updates for one automatically generated skill by slug")
	fs.StringVar(&opts.skillLearningDisable, "skill-learning-disable", "", "disable updates for one automatically generated skill by slug")
	fs.StringVar(&opts.skillLearningDelete, "skill-learning-delete", "", "delete one automatically generated skill by slug")
	fs.BoolVar(&opts.skillLearningEnableAll, "skill-learning-enable-all", false, "enable automatic skill learning in local state")
	fs.BoolVar(&opts.skillLearningDisableAll, "skill-learning-disable-all", false, "disable automatic skill learning in local state")
	fs.StringVar(&opts.skillLearningDir, "skill-learning-dir", "", "automatic skill learning state directory")
	fs.StringVar(&opts.skillLearningSkillDir, "skill-learning-skill-dir", "", "directory containing automatically generated skills")
	fs.BoolVar(&opts.speculatePlan, "speculate-plan", false, "print a speculative three-round execution plan and exit")
	fs.BoolVar(&opts.speculateRun, "speculate-run", false, "execute the full speculative three-round pipeline with real LLM calls and exit")
	fs.StringVar(&opts.speculatePrompt, "speculate-prompt", "", "base task prompt for --speculate-plan estimates or --speculate-run execution")
	fs.Var(&opts.routeCandidates, "route-candidate", "model route candidate spec: provider/model,key=value... (repeatable or comma-separated)")
	fs.Var(&opts.routeInputTokens, "route-input-tokens", "estimated input tokens for model routing")
	fs.Var(&opts.routeOutputTokens, "route-output-tokens", "estimated output tokens for model routing")
	fs.Var(&opts.routeCacheWriteTokens, "route-cache-write-tokens", "estimated prompt-cache write tokens for model routing")
	fs.Var(&opts.routeBudget, "route-budget", "maximum estimated request cost for model routing")
	fs.Var(&opts.routeCacheReuse, "route-cache-reuse", "prompt-cache reuse estimate for model routing (0..1)")
	fs.BoolVar(&opts.routeInteractive, "route-interactive", false, "rank model route candidates for low TTFT")
	fs.BoolVar(&opts.routeBatch, "route-batch", false, "rank model route candidates for batch/cost preference")
	fs.Var(&opts.speculateAgents, "speculate-agent", "agent name for --speculate-plan/--speculate-run (repeatable or comma-separated)")
	fs.Var(&opts.speculateGates, "speculate-gate", "required explicit gate check for --speculate-plan/--speculate-run (repeatable or comma-separated)")
	fs.Var(&opts.reviewAgents, "review-agent", "reviewer name for --review-plan/--review-run (repeatable or comma-separated)")
	fs.Var(&opts.reviewPaths, "review-path", "path for --review-plan/--review-run review surface (repeatable or comma-separated)")
	fs.Var(&opts.reviewGates, "review-gate", "required gate check for --review-plan/--review-run (repeatable or comma-separated)")
	fs.Var(&opts.skillMaxSteps, "skill-max-steps", "maximum repeated sequence length for --skill-step suggestions")
	fs.Var(&opts.skillMinOccurrences, "skill-min-occurrences", "minimum repeated occurrences for --skill-step suggestions")
	fs.StringVar(&opts.recordArtifact, "record-artifact", "", "record a session artifact path and exit")
	fs.StringVar(&opts.artifactKind, "artifact-kind", "", "kind for --record-artifact")
	fs.StringVar(&opts.artifactLogicalPath, "artifact-logical-path", "", "logical target path/decision for --record-artifact conflict detection")
	fs.StringVar(&opts.artifactReviewStatus, "artifact-review-status", "", "review status for --record-artifact")
	fs.StringVar(&opts.artifactSummary, "artifact-summary", "", "summary for --record-artifact")
	fs.StringVar(&opts.mergeArtifactsPath, "merge-artifacts", "", "write selected-session artifacts as a merged bundle; use '-' for stdout")
	fs.StringVar(&opts.mergeArtifactsFormat, "merge-artifacts-format", "markdown", "format for --merge-artifacts: markdown or json")
	fs.Var(&opts.mergeArtifactMaxBytes, "merge-artifact-max-bytes", "maximum bytes to read from each --merge-artifacts input")
	fs.StringVar(&opts.recordResponsePath, "record-response", "", "record a one-shot response to this JSON file")
	fs.StringVar(&opts.replayResponsePath, "replay-response", "", "replay a recorded one-shot response JSON file without calling an LLM")
	fs.Var(&opts.temperature, "temperature", "override request temperature")
	fs.Var(&opts.topP, "top-p", "override request nucleus sampling value (0..1)")
	fs.Var(&opts.maxTokens, "max-tokens", "override request max output tokens")
	fs.Var(&opts.seed, "seed", "best-effort deterministic seed for providers that support it")
	fs.StringVar(&opts.modelMode, "model-mode", "", "override request model mode (default or fast)")
	fs.StringVar(&opts.reasoningLevel, "reasoning-level", "", "override request reasoning level/effort")
	fs.Var(&opts.maxInputTokens, "max-input-tokens", "hard cap on estimated input tokens before an LLM call")
	fs.Var(&opts.contextPackTokens, "context-pack-tokens", "maximum estimated tokens for --context-pack-file; capped by --model context window when known")
	fs.Var(&opts.evaluationScore, "evaluation-score", "score for --record-evaluation")
	fs.Var(&opts.evaluationDurationMillis, "evaluation-duration-millis", "duration in milliseconds for --record-evaluation")
	fs.Var(&opts.evaluationPassRate, "evaluation-pass-rate", "pass rate for --record-evaluation (0..1)")
	fs.Var(&opts.evaluationFlakeCount, "evaluation-flake-count", "flake count for --record-evaluation")
	fs.Var(&opts.evaluationInputTokens, "evaluation-input-tokens", "input tokens for --record-evaluation")
	fs.Var(&opts.evaluationOutputTokens, "evaluation-output-tokens", "output tokens for --record-evaluation")
	fs.Var(&opts.evaluationTotalTokens, "evaluation-total-tokens", "total tokens for --record-evaluation")
	fs.Var(&opts.evaluationCost, "evaluation-cost", "cost for --record-evaluation")
	fs.Var(&opts.evaluationConfidence, "evaluation-confidence", "confidence for --record-evaluation (0..1)")
	fs.BoolVar(&opts.listModels, "list-models", false, "list available models and exit")
	fs.BoolVar(&opts.listKnownModels, "list-known-models", false, "list built-in provider/model IDs without API calls and exit")
	fs.BoolVar(&opts.listProviders, "list-providers", false, "list built-in provider names without API calls and exit")
	fs.StringVar(&opts.explainModelResolution, "explain-model-resolution", "", "explain how a model ID resolves to a provider and exit")
	fs.BoolVar(&opts.ollamaStatus, "ollama-status", false, "print Ollama daemon lifecycle status without starting it and exit")
	fs.BoolVar(&opts.ollamaStop, "ollama-stop", false, "stop and clean up the Atteler-owned Ollama daemon record and exit")
	fs.BoolVar(&opts.listAgents, "list-agents", false, "list configured agents and exit")
	fs.BoolVar(&opts.listCodeImports, "code-imports", false, "list Go import edges in the current repository and exit")
	fs.BoolVar(&opts.listCodeImportSummary, "code-import-summary", false, "list Go import paths with usage counts and exit")
	fs.BoolVar(&opts.listCodeImportFileSummary, "code-import-file-summary", false, "list Go files with import counts and exit")
	fs.BoolVar(&opts.listCodeLayers, "code-layers", false, "list topological Go import graph layers for the current repository and exit")
	fs.BoolVar(&opts.listCodeCycles, "code-cycles", false, "list Go import graph cycles for the current repository and exit")
	fs.BoolVar(&opts.codeSummary, "code-summary", false, "print compact Go code index and import graph counts and exit")
	fs.BoolVar(&opts.listCodeFiles, "code-files", false, "list Go files with package, import, and symbol counts and exit")
	fs.BoolVar(&opts.listCodeSymbolSummary, "code-symbol-summary", false, "list Go symbol kinds with counts and exit")
	fs.BoolVar(&opts.listCodeSymbolFileSummary, "code-symbol-file-summary", false, "list Go files with symbol counts and exit")
	fs.BoolVar(&opts.listCodePackages, "code-packages", false, "list Go packages with file and symbol counts and exit")
	fs.BoolVar(&opts.listCodePackageImportSummary, "code-package-import-summary", false, "list Go packages with import counts and exit")
	fs.BoolVar(&opts.listSessions, "list-sessions", false, "list saved sessions and exit")
	fs.BoolVar(&opts.listHeadless, "list-headless", false, "list active headless runs and exit")
	fs.BoolVar(&opts.recoverHeadless, "recover-headless", false, "reconcile stale/orphaned headless runs and exit")
	fs.StringVar(&opts.statusHeadlessID, "status-headless", "", "show one headless run status by headless ID and exit")
	fs.StringVar(&opts.cancelHeadlessID, "cancel-headless", "", "cancel one live headless run by headless ID and exit")
	fs.StringVar(&opts.streamHeadlessID, "stream-headless", "", "stream one headless run log by headless ID and exit when it finishes")
	fs.BoolVar(&opts.taskList, "task-list", false, "list persistent agent task/TODO items and exit")
	fs.BoolVar(&opts.listSessionTags, "list-session-tags", false, "list saved session tags with counts and exit")
	fs.BoolVar(&opts.agentPerformanceSummary, "agent-performance-summary", false, "summarize recorded agent performance across saved sessions and exit")
	fs.BoolVar(&opts.listArtifacts, "list-artifacts", false, "list artifacts recorded on the selected session and exit")
	fs.BoolVar(&opts.listEvaluations, "list-evaluations", false, "list agent evaluations recorded on the selected session and exit")
	fs.BoolVar(&opts.listFailures, "list-failures", false, "list negative-knowledge records on the selected session and exit")
	fs.BoolVar(&opts.listMessages, "list-messages", false, "list compact message records on the selected session and exit")
	fs.BoolVar(&opts.listRuns, "list-runs", false, "list review/speculation multi-agent runs recorded on the selected session and exit")
	fs.StringVar(&opts.listSessionsTag, "list-sessions-tag", "", "filter --list-sessions to sessions containing this exact tag")
	fs.BoolVar(&opts.listConfigPaths, "list-config-paths", false, "list config files in load order and exit")
	fs.BoolVar(&opts.listPlugins, "list-plugins", false, "list configured local plugin manifests and exit")
	fs.BoolVar(&opts.listHookEvents, "list-hook-events", false, "list supported lifecycle hook event types and exit")
	fs.BoolVar(&opts.listHookEventsJSON, "list-hook-events-json", false, "list supported lifecycle hook event types as JSON and exit")
	fs.BoolVar(&opts.stateDiagnostics, "state-diagnostics", false, "print persisted interactive state diagnostics and exit")
	fs.BoolVar(&opts.commandSurfaceJSON, "command-surface-json", false, "dump the inspectable CLI command surface as JSON and exit")
	fs.BoolVar(&opts.commandSurfaceDocs, "command-surface-docs", false, "render the inspectable CLI command surface as Markdown and exit")
	fs.BoolVar(&opts.watchScan, "watch-scan", false, "scan the current repository for background-agent health findings and exit")
	fs.BoolVar(&opts.watchJSON, "watch-json", false, "emit --watch-scan findings as JSON")
	fs.BoolVar(&opts.watchLoop, "watch-loop", false, "continuously scan the current repository for background-agent health findings")
	fs.StringVar(&opts.watchBaselinePath, "watch-baseline", "", "compare watch findings against a baseline JSON file from an earlier watch JSON scan")
	fs.StringVar(&opts.watchBaselineRef, "watch-baseline-ref", "", "compare watch findings against the git merge-base between HEAD and this ref")
	fs.StringVar(&opts.watchRulesPath, "watch-rules", "", "configure watch scan rules from a JSON file with rule_id, severity/help/owner overrides, or disabled=true")
	fs.StringVar(&opts.watchSuppressionsPath, "watch-suppressions", "", "apply watch finding suppressions from a JSON file with required reasons")
	fs.BoolVar(&opts.watchGate, "watch-gate", false, "fail watch scan/loop when new unsuppressed findings meet the gate severity")
	fs.StringVar(&opts.watchGateMinSeverity, "watch-gate-min-severity", "", "minimum severity for --watch-gate; defaults to high")
	fs.BoolVar(&opts.watchIssueUpsert, "watch-upsert-issues", false, "create or update GitHub issues for new unsuppressed watch findings meeting --watch-issue-min-severity")
	fs.StringVar(&opts.watchIssueMinSeverity, "watch-issue-min-severity", "", "minimum severity for --watch-upsert-issues; defaults to high")
	fs.StringVar(&opts.watchIssueRepository, "watch-github-repository", "", "GitHub repository owner/name for --watch-upsert-issues")
	fs.StringVar(&opts.watchGitHubEndpoint, "watch-github-api-url", "", "GitHub API endpoint for --watch-upsert-issues; defaults to https://api.github.com")
	fs.StringVar(&opts.watchGitHubToken, "watch-github-token", "", "GitHub token for --watch-upsert-issues; defaults to GITHUB_TOKEN or GH_TOKEN")
	fs.Var(&opts.watchIssueLabels, "watch-issue-label", "GitHub issue label for --watch-upsert-issues (repeatable or comma-separated; defaults to quality,watch)")
	fs.Var(&opts.watchIntervalSeconds, "watch-interval-seconds", "seconds between --watch-loop scans")
	fs.Var(&opts.watchMaxIterations, "watch-max-iterations", "maximum --watch-loop scans before exiting; omit to run until interrupted")
	fs.BoolVar(&opts.reviewPlan, "review-plan", false, "print speculative review-agent plan and exit")
	fs.BoolVar(&opts.reviewRun, "review-run", false, "execute the full review-agent three-round pipeline with real LLM calls and exit")
	fs.StringVar(&opts.reviewPrompt, "review-prompt", "", "additional review instructions for --review-run")
	fs.BoolVar(&opts.reviewScan, "review-scan", false, "scan the current repository and print a structured review report and exit")
	fs.BoolVar(&opts.feedbackProposals, "feedback-proposals", false, "derive agent improvement proposals from the selected session and exit")
	fs.StringVar(&opts.feedbackApplyConfig, "feedback-apply-config", "", "record feedback proposals from the selected session as pending guidance in this agent config file")
	fs.StringVar(&opts.feedbackApproveConfig, "feedback-approve-config", "", "approve one pending feedback guidance record in this agent config file")
	fs.StringVar(&opts.feedbackApproveAgent, "feedback-approve-agent", "", "agent name for --feedback-approve-config")
	fs.StringVar(&opts.feedbackApproveID, "feedback-approve-id", "", "guidance ID for --feedback-approve-config")
	fs.StringVar(&opts.feedbackRollbackConfig, "feedback-rollback-config", "", "roll back one feedback guidance record in this agent config file")
	fs.StringVar(&opts.feedbackRollbackAgent, "feedback-rollback-agent", "", "agent name for --feedback-rollback-config")
	fs.StringVar(&opts.feedbackRollbackID, "feedback-rollback-id", "", "guidance ID for --feedback-rollback-config")
	fs.StringVar(&opts.feedbackRollbackReason, "feedback-rollback-reason", "", "optional rollback reason for --feedback-rollback-config")
	fs.StringVar(&opts.feedbackHistoryPath, "feedback-history", "", "append feedback apply/rollback decisions to this history log")
	fs.Var(&opts.watchLargeFileBytes, "watch-large-file-bytes", "large-file byte threshold for --watch-scan")
	fs.BoolVar(&opts.configMigrate, "config-migrate", false, "migrate existing Atteler config/state files to the current schema and exit")
	fs.BoolVar(&opts.configReport, "config-report", false, "print redacted config diagnostics for issue reports and exit")
	fs.BoolVar(&opts.validateConfig, "validate-config", false, "validate merged YAML/JSON config and importer warnings, then exit")
	fs.BoolVar(&opts.explainConfig, "explain-config", false, "print merged config values with per-field provenance and exit")
	fs.StringVar(&opts.explainConfigPath, "explain-config-field", "", "limit --explain-config output to this field path prefix")
	fs.BoolVar(&opts.printConfigTemplate, "print-config-template", false, "print a starter YAML config and exit")
	fs.BoolVar(&opts.doctor, "doctor", false, "print local readiness diagnostics and exit")
	fs.BoolVar(&opts.doctorOffline, "doctor-offline", false, "print offline readiness diagnostics without provider health checks and exit")
	fs.BoolVar(&opts.readStdin, "stdin", false, "append stdin to a one-shot prompt")
	fs.BoolVar(&opts.headless, "headless", false, "run one-shot prompt without TUI output while recording headless metadata and logs")
	fs.StringVar(&opts.headlessID, "headless-id", "", "set the file-name run ID for a --headless one-shot run so automation can monitor or cancel it")
	fs.BoolVar(&opts.headlessPrivateLog, "headless-private-log", false, "store unredacted headless prompts, errors, event summaries, and logs; use only for local private runs")
	fs.BoolVar(&opts.showVersion, "version", false, "print version and exit")
	fs.BoolVar(&opts.useWorktree, "worktree", false, "isolate session in a git worktree")
	fs.BoolVar(&opts.worktreeAutoMerge, "worktree-auto-merge", false, "opt in to reviewed worktree auto-merge on session exit")
	fs.Var(&opts.worktreeVerificationCommands, "worktree-verify-command", "verification command to run inside the session worktree before merge (repeatable)")
	fs.BoolVar(&opts.worktreeMergeOverride, "worktree-merge-override", false, "explicitly allow worktree merge without verification commands")
	fs.BoolVar(&opts.listWorktrees, "list-worktrees", false, "list active atteler worktrees and exit")
	fs.BoolVar(&opts.noAutoMerge, "no-auto-merge", false, "keep worktree alive on exit (default; overrides configured auto-merge)")
	fs.StringVar(&opts.mergeWorktreeRef, "merge-worktree", "", "merge a session worktree back into its base branch and exit")
	fs.BoolVar(&opts.mergeWorktreeAllowBaseMismatch, "merge-worktree-allow-base-mismatch", false, "allow manual worktree merge when current branch differs from recorded base")
}
